export {
  INSTALLED_AUTOMATION_VERSION,
  climateInstalledAutomationSchema,
  createInstalledAutomation,
  createInstalledAutomationId,
  createStandalonePulseInstalledAutomation,
  createStandalonePulseInstalledAutomationId,
  createTimeInstalledAutomation,
  createTimeInstalledAutomationId,
  findInstalledRelayOwner,
  findRelayOwnerConflict,
  installedAutomationRelayId,
  installedAutomationSchema,
  isStandalonePulseInstalledAutomation,
  standalonePulseInstalledAutomationSchema,
  timeInstalledAutomationSchema,
  type ClimateInstalledAutomation,
  type InstalledAutomation,
  type InstalledAutomationKind,
  type StandalonePulseInstalledAutomation,
  type TimeInstalledAutomation
} from '../../features/automations/index.js';
