export {
  INSTALLED_AUTOMATION_VERSION,
  climateInstalledAutomationSchema,
  createInstalledAutomation,
  createInstalledAutomationId,
  createTimeInstalledAutomation,
  createTimeInstalledAutomationId,
  createTimePulseInstalledAutomation,
  findInstalledRelayOwner,
  findRelayOwnerConflict,
  installedAutomationRelayId,
  installedAutomationSchema,
  isTimePulseInstalledAutomation,
  timeInstalledAutomationSchema,
  type ClimateInstalledAutomation,
  type InstalledAutomation,
  type InstalledAutomationKind,
  type TimeInstalledAutomation,
  type TimePulseInstalledAutomation
} from '../../features/automations/index.js';
